In [2]:
import pandas as pd

In [3]:
# 1. Create a DataFrame for the 201908-citibike-tripdata data. 
df = pd.read_csv("../Resources/201908-citibike-tripdata.csv")

In [4]:
# 2. Check the datatypes of your columns. 
df.dtypes

tripduration                 int64
starttime                   object
stoptime                    object
start station id           float64
start station name          object
start station latitude     float64
start station longitude    float64
end station id             float64
end station name            object
end station latitude       float64
end station longitude      float64
bikeid                       int64
usertype                    object
birth year                   int64
gender                       int64
dtype: object

In [ ]:
import datetime as dt

In [18]:
# 3. Convert the 'tripduration' column to datetime datatype.
df.tripduration = pd.to_datetime(df.tripduration, unit='s').dt.time

In [19]:
# 4. Check the datatypes of your columns. 
df.dtypes

tripduration                object
starttime                   object
stoptime                    object
start station id           float64
start station name          object
start station latitude     float64
start station longitude    float64
end station id             float64
end station name            object
end station latitude       float64
end station longitude      float64
bikeid                       int64
usertype                    object
birth year                   int64
gender                       int64
dtype: object

In [20]:
df.sample(10)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
1877922,00:13:34,2019-08-25 18:33:29.7750,2019-08-25 18:47:03.8470,168.0,W 18 St & 6 Ave,40.739713,-73.994564,3712.0,W 35 St & Dyer Ave,40.754692,-73.997402,35347,Subscriber,1988,2
2194018,00:27:19,2019-08-29 20:16:46.5610,2019-08-29 20:44:05.7130,251.0,Mott St & Prince St,40.723180,-73.994800,372.0,Franklin Ave & Myrtle Ave,40.694546,-73.958014,20962,Subscriber,1988,1
850513,00:07:56,2019-08-12 06:43:57.0530,2019-08-12 06:51:53.0610,417.0,Barclay St & Church St,40.712912,-74.010202,249.0,Harrison St & Hudson St,40.718710,-74.009001,39892,Subscriber,1954,1
579138,00:26:49,2019-08-08 17:10:52.0920,2019-08-08 17:37:41.4720,358.0,Christopher St & Greenwich St,40.732916,-74.007114,3169.0,Riverside Dr & W 82 St,40.787209,-73.981281,33994,Subscriber,1986,1
423162,00:04:24,2019-08-06 11:23:37.6930,2019-08-06 11:28:02.5190,335.0,Washington Pl & Broadway,40.729039,-73.994046,303.0,Mercer St & Spring St,40.723627,-73.999496,32318,Subscriber,1993,2
42720,00:04:23,2019-08-01 15:53:33.8350,2019-08-01 15:57:57.5360,539.0,Metropolitan Ave & Bedford Ave,40.715348,-73.960241,3087.0,Metropolitan Ave & Meeker Ave,40.714133,-73.952344,30860,Subscriber,1990,2
1970020,00:05:13,2019-08-26 22:19:53.1470,2019-08-26 22:25:06.4240,3715.0,Driggs Ave & N 9 St,40.718170,-73.955201,3100.0,Nassau Ave & Newell St,40.724813,-73.947526,14824,Subscriber,1992,2
1700704,00:15:19,2019-08-23 12:50:17.4560,2019-08-23 13:05:36.8450,486.0,Broadway & W 29 St,40.746201,-73.988557,380.0,W 4 St & 7 Ave S,40.734011,-74.002939,29853,Subscriber,1987,1
403922,00:10:36,2019-08-06 07:43:02.6860,2019-08-06 07:53:39.1720,514.0,12 Ave & W 40 St,40.760875,-74.002777,470.0,W 20 St & 8 Ave,40.743453,-74.000040,33913,Subscriber,1986,1
998724,00:25:59,2019-08-13 21:19:42.1670,2019-08-13 21:45:41.3870,480.0,W 53 St & 10 Ave,40.766697,-73.990617,3707.0,Lexington Ave & E 26 St,40.741459,-73.983293,25665,Subscriber,1982,2

In [21]:
# 5. Export the Dataframe as a new CSV file without the index
df.to_csv("../Resources/Aug_citibike_data.csv", index=False)